<Project Sdk="Microsoft.NET.Sdk.Razor">
    <PropertyGroup>
        <TailwindCssInput>wwwroot\app.css</TailwindCssInput>
        <TailwindCssOutput>wwwroot\app.min.css</TailwindCssOutput>
    </PropertyGroup>

    <ItemGroup>
        <SupportedPlatform Include="browser" />
    </ItemGroup>

    <ItemGroup Label="Packages">
        <PackageReference Include="BlazorBlueprint.Icons.Heroicons" />
        <PackageReference Include="BlazorBlueprint.Primitives" />
        <PackageReference Include="Microsoft.Extensions.Localization.Abstractions" />
        <PackageReference Include="Microsoft.FluentUI.AspNetCore.Components" VersionOverride="4.11.5" />
        <PackageReference Include="TailwindMerge.NET" />
    </ItemGroup>

    <ItemGroup>
        <Content Remove="wwwroot\ts\**\*" />
    </ItemGroup>

    <ItemGroup>
        <None Include="wwwroot\ts\**\*">
            <CopyToOutputDirectory>Never</CopyToOutputDirectory>
            <CopyToPublishDirectory>Never</CopyToPublishDirectory>
        </None>
    </ItemGroup>

    <Import Project="..\..\.targets\TailwindIntegration.targets" />
</Project>