//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pl.Admin.Client.Source.Shared.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationResources_ru_RU {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationResources_ru_RU() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pl.Admin.Client.Source.Shared.Localization.ApplicationResources.ru-RU", typeof(ApplicationResources_ru_RU).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось добавить {0} ПЛУ к АРМ.
        /// </summary>
        public static string ArmPluAddedUnsuccessfully {
            get {
                return ResourceManager.GetString("ArmPluAddedUnsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не удалось убрать {0} ПЛУ с АРМ.
        /// </summary>
        public static string ArmPluRemovedUnsuccessfully {
            get {
                return ResourceManager.GetString("ArmPluRemovedUnsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Компьютер.
        /// </summary>
        public static string ArmTypeEnumPc {
            get {
                return ResourceManager.GetString("ArmTypeEnumPc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Моноблок.
        /// </summary>
        public static string ArmTypeEnumTablet {
            get {
                return ResourceManager.GetString("ArmTypeEnumTablet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Универсальный.
        /// </summary>
        public static string ArmTypeEnumUniversal {
            get {
                return ResourceManager.GetString("ArmTypeEnumUniversal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите константу....
        /// </summary>
        public static string BarcodeEditorConstInputPlaceholder {
            get {
                return ResourceManager.GetString("BarcodeEditorConstInputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отсутствуют поля.
        /// </summary>
        public static string BarcodeEditorEmptyPlaceholder {
            get {
                return ResourceManager.GetString("BarcodeEditorEmptyPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите маску....
        /// </summary>
        public static string BarcodeEditorMaskPlaceholder {
            get {
                return ResourceManager.GetString("BarcodeEditorMaskPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите переменную....
        /// </summary>
        public static string BarcodeEditorVariableSelectPlaceholder {
            get {
                return ResourceManager.GetString("BarcodeEditorVariableSelectPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Добавить.
        /// </summary>
        public static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Назад.
        /// </summary>
        public static string BtnBack {
            get {
                return ResourceManager.GetString("BtnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Отмена.
        /// </summary>
        public static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string BtnDelete {
            get {
                return ResourceManager.GetString("BtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Обновить.
        /// </summary>
        public static string BtnRefetch {
            get {
                return ResourceManager.GetString("BtnRefetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Восстановить.
        /// </summary>
        public static string BtnReset {
            get {
                return ResourceManager.GetString("BtnReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поделиться.
        /// </summary>
        public static string BtnShare {
            get {
                return ResourceManager.GetString("BtnShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Подтвердить.
        /// </summary>
        public static string BtnSubmit {
            get {
                return ResourceManager.GetString("BtnSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить.
        /// </summary>
        public static string BtnUpdate {
            get {
                return ResourceManager.GetString("BtnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удалить.
        /// </summary>
        public static string DataGridContextMenuDelete {
            get {
                return ResourceManager.GetString("DataGridContextMenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Просмотр.
        /// </summary>
        public static string DataGridContextMenuOpen {
            get {
                return ResourceManager.GetString("DataGridContextMenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Открыть в новой вкладке.
        /// </summary>
        public static string DataGridContextMenuOpenInNewTab {
            get {
                return ResourceManager.GetString("DataGridContextMenuOpenInNewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Изменить.
        /// </summary>
        public static string DataGridContextMenuUpdate {
            get {
                return ResourceManager.GetString("DataGridContextMenuUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to элементов.
        /// </summary>
        public static string DataGridTotalItems {
            get {
                return ResourceManager.GetString("DataGridTotalItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Это действие невозможно отменить. Это приведет к безвозвратному удалению элемента с сервера..
        /// </summary>
        public static string DeleteDialogDescription {
            get {
                return ResourceManager.GetString("DeleteDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы уверен что хотите удалить элемент?.
        /// </summary>
        public static string DeleteDialogTitle {
            get {
                return ResourceManager.GetString("DeleteDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Общая информация.
        /// </summary>
        public static string FieldCommon {
            get {
                return ResourceManager.GetString("FieldCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Местоположение.
        /// </summary>
        public static string FieldLocation {
            get {
                return ResourceManager.GetString("FieldLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Упаковка.
        /// </summary>
        public static string FieldPackaging {
            get {
                return ResourceManager.GetString("FieldPackaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Параметры.
        /// </summary>
        public static string FieldParameters {
            get {
                return ResourceManager.GetString("FieldParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Переавторизировать.
        /// </summary>
        public static string FormActionRelogin {
            get {
                return ResourceManager.GetString("FormActionRelogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сброс.
        /// </summary>
        public static string FormActionReset {
            get {
                return ResourceManager.GetString("FormActionReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Действия.
        /// </summary>
        public static string FormActionsTitle {
            get {
                return ResourceManager.GetString("FormActionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление принтером.
        /// </summary>
        public static string FormPrinterControl {
            get {
                return ResourceManager.GetString("FormPrinterControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите принтер.
        /// </summary>
        public static string FormPrinterDefaultPlaceholder {
            get {
                return ResourceManager.GetString("FormPrinterDefaultPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите площадку.
        /// </summary>
        public static string FormProductionSiteDefaultPlaceholder {
            get {
                return ResourceManager.GetString("FormProductionSiteDefaultPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пустой результат.
        /// </summary>
        public static string FormSelectEmptyDefaultPlaceholder {
            get {
                return ResourceManager.GetString("FormSelectEmptyDefaultPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поиск....
        /// </summary>
        public static string FormSelectSearchDefaultPlaceholder {
            get {
                return ResourceManager.GetString("FormSelectSearchDefaultPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите шаблон.
        /// </summary>
        public static string FormTemplateDefaultPlaceholder {
            get {
                return ResourceManager.GetString("FormTemplateDefaultPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выберите склад.
        /// </summary>
        public static string FormWarehouseDefaultPlaceholder {
            get {
                return ResourceManager.GetString("FormWarehouseDefaultPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Введите значение....
        /// </summary>
        public static string InputDefaultPlaceholder {
            get {
                return ResourceManager.GetString("InputDefaultPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ошибка ковертации zpl кода в изображение.
        /// </summary>
        public static string LabelsPreviewErrorMsg {
            get {
                return ResourceManager.GetString("LabelsPreviewErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Данные из 1С.
        /// </summary>
        public static string Menu1CReferences {
            get {
                return ResourceManager.GetString("Menu1CReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Администрирование.
        /// </summary>
        public static string MenuAdministration {
            get {
                return ResourceManager.GetString("MenuAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Устройства.
        /// </summary>
        public static string MenuDevices {
            get {
                return ResourceManager.GetString("MenuDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Диагностика.
        /// </summary>
        public static string MenuDiagnostics {
            get {
                return ResourceManager.GetString("MenuDiagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Операции.
        /// </summary>
        public static string MenuOperations {
            get {
                return ResourceManager.GetString("MenuOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Настройки печати.
        /// </summary>
        public static string MenuPrintSettings {
            get {
                return ResourceManager.GetString("MenuPrintSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Справочник.
        /// </summary>
        public static string MenuReferences {
            get {
                return ResourceManager.GetString("MenuReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Такой страницы не существует.
        /// </summary>
        public static string NotFoundMessage {
            get {
                return ResourceManager.GetString("NotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Если вы видите пустой блок, это означает, что браузер блокирует запрос к принтеру через сайт. Вы можете перейти по {0} на устройство или отключить настройки защиты браузера для сайта, следуя {1}..
        /// </summary>
        public static string PrinterControlDescription {
            get {
                return ResourceManager.GetString("PrinterControlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to прямой ссылке.
        /// </summary>
        public static string PrinterControlDescriptionDirectLink {
            get {
                return ResourceManager.GetString("PrinterControlDescriptionDirectLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to данному руководству.
        /// </summary>
        public static string PrinterControlDescriptionGuideLink {
            get {
                return ResourceManager.GetString("PrinterControlDescriptionGuideLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Удаленное управление принтером.
        /// </summary>
        public static string PrinterControlTitle {
            get {
                return ResourceManager.GetString("PrinterControlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Площадка не настроена для данного аккаунта. Обратитесь к поддержке..
        /// </summary>
        public static string ProductionSiteSuspenseDescription {
            get {
                return ResourceManager.GetString("ProductionSiteSuspenseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to АРМ.
        /// </summary>
        public static string SectionArm {
            get {
                return ResourceManager.GetString("SectionArm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARM ПЛУ.
        /// </summary>
        public static string SectionArmPlu {
            get {
                return ResourceManager.GetString("SectionArmPlu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Коробки.
        /// </summary>
        public static string SectionBoxes {
            get {
                return ResourceManager.GetString("SectionBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Бренды.
        /// </summary>
        public static string SectionBrands {
            get {
                return ResourceManager.GetString("SectionBrands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пакеты.
        /// </summary>
        public static string SectionBundles {
            get {
                return ResourceManager.GetString("SectionBundles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Клипсы.
        /// </summary>
        public static string SectionClips {
            get {
                return ResourceManager.GetString("SectionClips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Миграции.
        /// </summary>
        public static string SectionMigrations {
            get {
                return ResourceManager.GetString("SectionMigrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сдатчики.
        /// </summary>
        public static string SectionPalletMen {
            get {
                return ResourceManager.GetString("SectionPalletMen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПЛУ.
        /// </summary>
        public static string SectionPlu {
            get {
                return ResourceManager.GetString("SectionPlu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ПЛУ Характеристики.
        /// </summary>
        public static string SectionPluCharacteristics {
            get {
                return ResourceManager.GetString("SectionPluCharacteristics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Принтеры.
        /// </summary>
        public static string SectionPrinters {
            get {
                return ResourceManager.GetString("SectionPrinters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Площадки.
        /// </summary>
        public static string SectionProductionSites {
            get {
                return ResourceManager.GetString("SectionProductionSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Таблицы.
        /// </summary>
        public static string SectionTables {
            get {
                return ResourceManager.GetString("SectionTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ресурсы шаблонов.
        /// </summary>
        public static string SectionTemplateResources {
            get {
                return ResourceManager.GetString("SectionTemplateResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Шаблоны.
        /// </summary>
        public static string SectionTemplates {
            get {
                return ResourceManager.GetString("SectionTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Пользователи.
        /// </summary>
        public static string SectionUsers {
            get {
                return ResourceManager.GetString("SectionUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аналитика.
        /// </summary>
        public static string SectionViewAnalytics {
            get {
                return ResourceManager.GetString("SectionViewAnalytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Управление.
        /// </summary>
        public static string SectionViewControl {
            get {
                return ResourceManager.GetString("SectionViewControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Информация.
        /// </summary>
        public static string SectionViewInfo {
            get {
                return ResourceManager.GetString("SectionViewInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Предпросмотр.
        /// </summary>
        public static string SectionViewPreview {
            get {
                return ResourceManager.GetString("SectionViewPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Аналитика линии по смене.
        /// </summary>
        public static string SectionViewWorkshiftArmAnalytics {
            get {
                return ResourceManager.GetString("SectionViewWorkshiftArmAnalytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Этикетки смены.
        /// </summary>
        public static string SectionViewWorkshiftLabels {
            get {
                return ResourceManager.GetString("SectionViewWorkshiftLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Паллеты смены.
        /// </summary>
        public static string SectionViewWorkshiftPallets {
            get {
                return ResourceManager.GetString("SectionViewWorkshiftPallets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Склады.
        /// </summary>
        public static string SectionWarehouses {
            get {
                return ResourceManager.GetString("SectionWarehouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Не выбран.
        /// </summary>
        public static string SelectItemNotSelected {
            get {
                return ResourceManager.GetString("SelectItemNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вы можете либо скопировать ссылку вручную, либо воспользоваться встроенными функционалами социальных сетей.
        /// </summary>
        public static string ShareDialogDescription {
            get {
                return ResourceManager.GetString("ShareDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Поделиться записью.
        /// </summary>
        public static string ShareDialogTitle {
            get {
                return ResourceManager.GetString("ShareDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Выкл.
        /// </summary>
        public static string StateOff {
            get {
                return ResourceManager.GetString("StateOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вкл.
        /// </summary>
        public static string StateOn {
            get {
                return ResourceManager.GetString("StateOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Темная.
        /// </summary>
        public static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Светлая.
        /// </summary>
        public static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Системная.
        /// </summary>
        public static string ThemeSystem {
            get {
                return ResourceManager.GetString("ThemeSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значение сохранено в буфер обмена.
        /// </summary>
        public static string ToastCopyToClipboard {
            get {
                return ResourceManager.GetString("ToastCopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объект успешно создан.
        /// </summary>
        public static string ToastCreateItem {
            get {
                return ResourceManager.GetString("ToastCreateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объект успешно удален.
        /// </summary>
        public static string ToastDeleteItem {
            get {
                return ResourceManager.GetString("ToastDeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повторных вход систему выполнен.
        /// </summary>
        public static string ToastReloginUser {
            get {
                return ResourceManager.GetString("ToastReloginUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Исходные значения восстановлены.
        /// </summary>
        public static string ToastResetItem {
            get {
                return ResourceManager.GetString("ToastResetItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Объект успешно обновлен.
        /// </summary>
        public static string ToastUpdateItem {
            get {
                return ResourceManager.GetString("ToastUpdateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Неизвестная ошибка.
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Значок.
        /// </summary>
        public static string ZplResourceTypeEnumSign {
            get {
                return ResourceManager.GetString("ZplResourceTypeEnumSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Текст.
        /// </summary>
        public static string ZplResourceTypeEnumText {
            get {
                return ResourceManager.GetString("ZplResourceTypeEnumText", resourceCulture);
            }
        }
    }
}
