//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pl.Admin.Client.Source.Shared.Localization {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ApplicationResources_en_US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ApplicationResources_en_US() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pl.Admin.Client.Source.Shared.Localization.ApplicationResources.en-US", typeof(ApplicationResources_en_US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to add {0} PLU to the arm.
        /// </summary>
        public static string ArmPluAddedUnsuccessfully {
            get {
                return ResourceManager.GetString("ArmPluAddedUnsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to remove {0} PLU from the arm.
        /// </summary>
        public static string ArmPluRemovedUnsuccessfully {
            get {
                return ResourceManager.GetString("ArmPluRemovedUnsuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PC.
        /// </summary>
        public static string ArmTypeEnumPc {
            get {
                return ResourceManager.GetString("ArmTypeEnumPc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tablet.
        /// </summary>
        public static string ArmTypeEnumTablet {
            get {
                return ResourceManager.GetString("ArmTypeEnumTablet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Universal.
        /// </summary>
        public static string ArmTypeEnumUniversal {
            get {
                return ResourceManager.GetString("ArmTypeEnumUniversal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the const....
        /// </summary>
        public static string BarcodeEditorConstInputPlaceholder {
            get {
                return ResourceManager.GetString("BarcodeEditorConstInputPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field are missing.
        /// </summary>
        public static string BarcodeEditorEmptyPlaceholder {
            get {
                return ResourceManager.GetString("BarcodeEditorEmptyPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the mask....
        /// </summary>
        public static string BarcodeEditorMaskPlaceholder {
            get {
                return ResourceManager.GetString("BarcodeEditorMaskPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select variable....
        /// </summary>
        public static string BarcodeEditorVariableSelectPlaceholder {
            get {
                return ResourceManager.GetString("BarcodeEditorVariableSelectPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string BtnAdd {
            get {
                return ResourceManager.GetString("BtnAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string BtnBack {
            get {
                return ResourceManager.GetString("BtnBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string BtnCancel {
            get {
                return ResourceManager.GetString("BtnCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string BtnDelete {
            get {
                return ResourceManager.GetString("BtnDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refetch.
        /// </summary>
        public static string BtnRefetch {
            get {
                return ResourceManager.GetString("BtnRefetch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string BtnReset {
            get {
                return ResourceManager.GetString("BtnReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share.
        /// </summary>
        public static string BtnShare {
            get {
                return ResourceManager.GetString("BtnShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string BtnSubmit {
            get {
                return ResourceManager.GetString("BtnSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string BtnUpdate {
            get {
                return ResourceManager.GetString("BtnUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string DataGridContextMenuDelete {
            get {
                return ResourceManager.GetString("DataGridContextMenuDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        public static string DataGridContextMenuOpen {
            get {
                return ResourceManager.GetString("DataGridContextMenuOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in new tab.
        /// </summary>
        public static string DataGridContextMenuOpenInNewTab {
            get {
                return ResourceManager.GetString("DataGridContextMenuOpenInNewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string DataGridContextMenuUpdate {
            get {
                return ResourceManager.GetString("DataGridContextMenuUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to items.
        /// </summary>
        public static string DataGridTotalItems {
            get {
                return ResourceManager.GetString("DataGridTotalItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This action cannot be undone. This will permanently delete the item from the server..
        /// </summary>
        public static string DeleteDialogDescription {
            get {
                return ResourceManager.GetString("DeleteDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete the item?.
        /// </summary>
        public static string DeleteDialogTitle {
            get {
                return ResourceManager.GetString("DeleteDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        public static string FieldCommon {
            get {
                return ResourceManager.GetString("FieldCommon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location.
        /// </summary>
        public static string FieldLocation {
            get {
                return ResourceManager.GetString("FieldLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Packaging.
        /// </summary>
        public static string FieldPackaging {
            get {
                return ResourceManager.GetString("FieldPackaging", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameters.
        /// </summary>
        public static string FieldParameters {
            get {
                return ResourceManager.GetString("FieldParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Relogin.
        /// </summary>
        public static string FormActionRelogin {
            get {
                return ResourceManager.GetString("FormActionRelogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string FormActionReset {
            get {
                return ResourceManager.GetString("FormActionReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string FormActionsTitle {
            get {
                return ResourceManager.GetString("FormActionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printer control.
        /// </summary>
        public static string FormPrinterControl {
            get {
                return ResourceManager.GetString("FormPrinterControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the printer.
        /// </summary>
        public static string FormPrinterDefaultPlaceholder {
            get {
                return ResourceManager.GetString("FormPrinterDefaultPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the production site.
        /// </summary>
        public static string FormProductionSiteDefaultPlaceholder {
            get {
                return ResourceManager.GetString("FormProductionSiteDefaultPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results.
        /// </summary>
        public static string FormSelectEmptyDefaultPlaceholder {
            get {
                return ResourceManager.GetString("FormSelectEmptyDefaultPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search....
        /// </summary>
        public static string FormSelectSearchDefaultPlaceholder {
            get {
                return ResourceManager.GetString("FormSelectSearchDefaultPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the template.
        /// </summary>
        public static string FormTemplateDefaultPlaceholder {
            get {
                return ResourceManager.GetString("FormTemplateDefaultPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select the warehouse.
        /// </summary>
        public static string FormWarehouseDefaultPlaceholder {
            get {
                return ResourceManager.GetString("FormWarehouseDefaultPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter value....
        /// </summary>
        public static string InputDefaultPlaceholder {
            get {
                return ResourceManager.GetString("InputDefaultPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error while converting zpl code to image.
        /// </summary>
        public static string LabelsPreviewErrorMsg {
            get {
                return ResourceManager.GetString("LabelsPreviewErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1C References.
        /// </summary>
        public static string Menu1CReferences {
            get {
                return ResourceManager.GetString("Menu1CReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administration.
        /// </summary>
        public static string MenuAdministration {
            get {
                return ResourceManager.GetString("MenuAdministration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        public static string MenuDevices {
            get {
                return ResourceManager.GetString("MenuDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diagnostics.
        /// </summary>
        public static string MenuDiagnostics {
            get {
                return ResourceManager.GetString("MenuDiagnostics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operations.
        /// </summary>
        public static string MenuOperations {
            get {
                return ResourceManager.GetString("MenuOperations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print settings.
        /// </summary>
        public static string MenuPrintSettings {
            get {
                return ResourceManager.GetString("MenuPrintSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to References.
        /// </summary>
        public static string MenuReferences {
            get {
                return ResourceManager.GetString("MenuReferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This page could not be found.
        /// </summary>
        public static string NotFoundMessage {
            get {
                return ResourceManager.GetString("NotFoundMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you see an empty block, it means that the browser is blocking the request to the printer through the site. You can follow the {0} to the device or disable the browser security settings for the site by following {1}..
        /// </summary>
        public static string PrinterControlDescription {
            get {
                return ResourceManager.GetString("PrinterControlDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to direct link.
        /// </summary>
        public static string PrinterControlDescriptionDirectLink {
            get {
                return ResourceManager.GetString("PrinterControlDescriptionDirectLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this guide.
        /// </summary>
        public static string PrinterControlDescriptionGuideLink {
            get {
                return ResourceManager.GetString("PrinterControlDescriptionGuideLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote printer control.
        /// </summary>
        public static string PrinterControlTitle {
            get {
                return ResourceManager.GetString("PrinterControlTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The platform is not configured for this account. Contact support..
        /// </summary>
        public static string ProductionSiteSuspenseDescription {
            get {
                return ResourceManager.GetString("ProductionSiteSuspenseDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARM.
        /// </summary>
        public static string SectionArm {
            get {
                return ResourceManager.GetString("SectionArm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ARM PLU.
        /// </summary>
        public static string SectionArmPlu {
            get {
                return ResourceManager.GetString("SectionArmPlu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boxes.
        /// </summary>
        public static string SectionBoxes {
            get {
                return ResourceManager.GetString("SectionBoxes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brands.
        /// </summary>
        public static string SectionBrands {
            get {
                return ResourceManager.GetString("SectionBrands", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bundles.
        /// </summary>
        public static string SectionBundles {
            get {
                return ResourceManager.GetString("SectionBundles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clips.
        /// </summary>
        public static string SectionClips {
            get {
                return ResourceManager.GetString("SectionClips", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migrations.
        /// </summary>
        public static string SectionMigrations {
            get {
                return ResourceManager.GetString("SectionMigrations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pallet Men.
        /// </summary>
        public static string SectionPalletMen {
            get {
                return ResourceManager.GetString("SectionPalletMen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLU.
        /// </summary>
        public static string SectionPlu {
            get {
                return ResourceManager.GetString("SectionPlu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PLU Characteristics.
        /// </summary>
        public static string SectionPluCharacteristics {
            get {
                return ResourceManager.GetString("SectionPluCharacteristics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printers.
        /// </summary>
        public static string SectionPrinters {
            get {
                return ResourceManager.GetString("SectionPrinters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Production Sites.
        /// </summary>
        public static string SectionProductionSites {
            get {
                return ResourceManager.GetString("SectionProductionSites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tables.
        /// </summary>
        public static string SectionTables {
            get {
                return ResourceManager.GetString("SectionTables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates Resources.
        /// </summary>
        public static string SectionTemplateResources {
            get {
                return ResourceManager.GetString("SectionTemplateResources", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Templates.
        /// </summary>
        public static string SectionTemplates {
            get {
                return ResourceManager.GetString("SectionTemplates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string SectionUsers {
            get {
                return ResourceManager.GetString("SectionUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analytics.
        /// </summary>
        public static string SectionViewAnalytics {
            get {
                return ResourceManager.GetString("SectionViewAnalytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Control.
        /// </summary>
        public static string SectionViewControl {
            get {
                return ResourceManager.GetString("SectionViewControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string SectionViewInfo {
            get {
                return ResourceManager.GetString("SectionViewInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        public static string SectionViewPreview {
            get {
                return ResourceManager.GetString("SectionViewPreview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work shift arm analytics.
        /// </summary>
        public static string SectionViewWorkshiftArmAnalytics {
            get {
                return ResourceManager.GetString("SectionViewWorkshiftArmAnalytics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work shift labels.
        /// </summary>
        public static string SectionViewWorkshiftLabels {
            get {
                return ResourceManager.GetString("SectionViewWorkshiftLabels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work shift pallets.
        /// </summary>
        public static string SectionViewWorkshiftPallets {
            get {
                return ResourceManager.GetString("SectionViewWorkshiftPallets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warehouses.
        /// </summary>
        public static string SectionWarehouses {
            get {
                return ResourceManager.GetString("SectionWarehouses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not selected.
        /// </summary>
        public static string SelectItemNotSelected {
            get {
                return ResourceManager.GetString("SelectItemNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can either copy the link manually, or use the built-in functionality of social networks.
        /// </summary>
        public static string ShareDialogDescription {
            get {
                return ResourceManager.GetString("ShareDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Share an entry.
        /// </summary>
        public static string ShareDialogTitle {
            get {
                return ResourceManager.GetString("ShareDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        public static string StateOff {
            get {
                return ResourceManager.GetString("StateOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        public static string StateOn {
            get {
                return ResourceManager.GetString("StateOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark.
        /// </summary>
        public static string ThemeDark {
            get {
                return ResourceManager.GetString("ThemeDark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        public static string ThemeLight {
            get {
                return ResourceManager.GetString("ThemeLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System.
        /// </summary>
        public static string ThemeSystem {
            get {
                return ResourceManager.GetString("ThemeSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value copied to clipboard.
        /// </summary>
        public static string ToastCopyToClipboard {
            get {
                return ResourceManager.GetString("ToastCopyToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item was created.
        /// </summary>
        public static string ToastCreateItem {
            get {
                return ResourceManager.GetString("ToastCreateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item was deleted.
        /// </summary>
        public static string ToastDeleteItem {
            get {
                return ResourceManager.GetString("ToastDeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A relogin has been executed.
        /// </summary>
        public static string ToastReloginUser {
            get {
                return ResourceManager.GetString("ToastReloginUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original values restored.
        /// </summary>
        public static string ToastResetItem {
            get {
                return ResourceManager.GetString("ToastResetItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The item was updated.
        /// </summary>
        public static string ToastUpdateItem {
            get {
                return ResourceManager.GetString("ToastUpdateItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown error.
        /// </summary>
        public static string UnknownError {
            get {
                return ResourceManager.GetString("UnknownError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign.
        /// </summary>
        public static string ZplResourceTypeEnumSign {
            get {
                return ResourceManager.GetString("ZplResourceTypeEnumSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        public static string ZplResourceTypeEnumText {
            get {
                return ResourceManager.GetString("ZplResourceTypeEnumText", resourceCulture);
            }
        }
    }
}
